import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Header from "./components/Header"
import Sidenav from "./components/SideNav"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<Sidenav />
			</main>

			<style jsx>
				{`
					main {
						height: calc(100vh - 50px);
						max-height: 100vh;
						overflow-x: auto;
						overflow-y: hidden;
						display: flex;
					}
				`}
			</style>
		</>
	)
}
